#!/usr/bin/env bash
# This script installs and configures HAProxy for load balancing between web-01 and web-02 servers

# Update the package list
apt-get update

# Install HAProxy
apt-get install -y haproxy

# Enable HAProxy to start on boot
sed -i '/ENABLED=/c\ENABLED=1' /etc/default/haproxy

# Configure HAProxy to use roundrobin algorithm and distribute traffic to web-01 and web-02
echo 'global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 54.221.188.119:80 check
    server web-02 3.89.155.140:80 check' > /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the configuration
service haproxy restart
