#!/usr/bin/env bash
# This script creates a PID file and handles various signals.

# Create the PID file with the current PID
echo $$ > /var/run/myscript.pid

# Signal handling
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# Infinite loop to display "To infinity and beyond"
while true
do
  echo "To infinity and beyond"
  sleep 2
done
