#!/usr/bin/env bash
# This script modifies the /etc/hosts file to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8.

sudo sed -i '/127.0.0.1/s/127.0.0.1/127.0.0.2/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
