#!/usr/bin/env bash
# This script creates an RSA key pair named 'school' with 4096 bits and passphrase 'betty'.
ssh-keygen -b 4096 -N betty -f /home/elkomy/AlxSE/alx-system_engineering-devops/0x0B-ssh/school
