#!/usr/bin/env bash
# This script creates an RSA key pair named 'school' with 4096 bits and passphrase 'betty'.
# The keys will be saved in the current project directory.

ssh-keygen -t rsa -b 4096 -f /home/elkomy/AlxSE/alx-system_engineering-devops/0x0B-ssh/school -N "betty"
